language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_script:
  - sudo mkdir -p /var/log/MRMedia/backend/
  - sudo touch /var/log/MRMedia/backend/mrmedia-backweb.log
  - sudo chmod 777 /var/log/MRMedia/backend/mrmedia-backweb.log

script:
  - gradle test

after_success:
  - gradle jacocoTestReport coveralls
