language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_script:
  - mkdir -p /var/log/MRMedia/backend/
  - touch /var/log/MRMedia/backend/mrmedia-backweb.log

script:
  - gradle test --debug

after_success:
  - gradle jacoco
  - gradle jacocoTestReport coveralls
