language: java

jdk:
  - oraclejdk8

before_install:
  - java -version
  - gradle check
  - gradle -v

install:
  - gradle build

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
