language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_install:
  - gradle check

install:
  - gradle build
  - gradle test

after_success:
  - gradle jacoco
  - gradle jacocoTestReport coveralls
