language: java

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

jdk:
  - oraclejdk8

services:
  - mysql

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
  - gradle test

after_success:
  - gradle jacoco
  - gradle jacocoTestReport coveralls
